destinations/config/routes.rb
Rails.application.routes.draw do
  root to: "users#home"

  get "/users", to: "users#index", as: "users"
  get "/users/new", to: "users#new", as: "new_user"
  post "/users", to: "users#create"
  get "/users/:id", to: "users#show", as: "user"
  get "/users/:id/edit", to: "users#edit"
  patch "/users/:id", to: "users#update"
  
  get "/sign_in", to: "sessions#new"
  
  post "/sessions", to: "sessions#create"
  delete "/sessions", to: "sessions#destroy", as: "delete"
  
  resources :venues
end

destinations/app/models/user.rb
class User < ActiveRecord::Base
  has_many :visits
  has_many :venues, through: :visits
  
  has_secure_password

  def self.confirm(params)
    @user = User.find_by({email: params[:email]})
    @user.try(:authenticate, params[:password])
  end

end

destinations/app/models/venue.rb
class Venue < ActiveRecord::Base
  has_many :visits
  has_many :users, through: :visits
end

destinations/app/models/visit.rb
class Visit < ActiveRecord::Base
  belongs_to :user
  belongs_to :venue
end

destinations/app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception

  include SessionsHelper

  # before_filter :require_login

  # private

  # def require_login
  #   unless current_user
  #     redirect_to '/'
  #   end
  # end


end

destinations/app/controllers/sessions_controller.rb
class SessionsController < ApplicationController

  # skip_before_filter :require_login

  def new
    @user = User.new
    render :new
  end

  def create
    user_params = params.require(:user).permit(:email, :password)
    @user = User.confirm(user_params)
    if @user
      login(@user)
      redirect_to "/users/#{@user.id}"
    else
      redirect_to "/sign_in"
    end
  end

  def destroy
    logout
    redirect_to root_path
  end

end

destinations/app/controllers/users_controller.rb
class UsersController < ApplicationController
  
  def home
      render :home
  end

  def index
    @users = User.all
    render :index
  end

  def new
    @user = User.new
    render :new
  end

  def create
    @user = User.new(user_params)
    if @user.save
      login(@user)
      redirect_to "/users/#{@user.id}"
    else
      redirect_to new_users_path
    end
  end

  def edit
    @user = User.find(params[:id])
    render :edit
  end

  def show
    @user = User.find(params[:id])

     if current_user == nil
      redirect_to "/sign_in"
    else
      render :show
    end
  end

  def update
    @user = User.find(params[:id])
    @user.update_attributes(user_params)
    redirect_to @user
  end

  private
  def user_params
    params.require(:user).permit(:first_name, :last_name, :email, :password, :age, :profile_pic, :description, :current_city)
  end

end

destinations/app/controllers/venues_controller.rb
class VenuesController < ApplicationController

  def index
    @venues = Venue.all.order(id: :desc)
    render :index
  end

  def new
    @venue = Venue.new
    render :new
  end

  def create
    @venue = Venue.new(venue_params)
    if @venue.save
      redirect_to @venue
    else
      redirect_to new_venue_path
    end
  end

  def show
    @venue = Venue.find(params[:id])
    render :show
  end


  private
  def venue_params
    params.require(:venue).permit(:name, :street_one, :street_two, :city, :state, :zipcode, :phone_number, :email, :description, :profile_pic)
  end

end

destinations/app/helpers/sessions_helper.rb
module SessionsHelper
  def login(user)
    session[:user_id] = user.id
    @current_user = user
  end

  def current_user
    @current_user ||= session[:user_id] && User.find(session[:user_id])
  end

  def logged_in?
    if current_user == nil
      redirect_to "/sign_in"
    end
  end

  def logout
    session.delete(:user_id)
    @current_user = nil
  end

end
  

destinations/app/helpers/users_helper.rb
module UsersHelper
end

destinations/app/helpers/venues_helper.rb
module VenuesHelper
end

destinations/app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
   <!-- Compiled and minified CSS -->
  <link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/materialize/0.97.6/css/materialize.min.css">
  <nav class="teal">
    <div class="nav-wrapper">
      <a href="/" class="brand-logo">Destinations</a>
      <ul id="nav-mobile" class="right hide-on-med-and-down">
      <% if current_user %>
        <li>You are logged in <%= current_user.first_name %> </li>
        <li><%= link_to "Sign Out", sessions_path, method: :delete %></li>
      <% else %>
        <li><%= link_to "Sign in", sign_in_path, method: :get%></li>
        <li><%= link_to "Sign up", new_user_path, method: :get%></li>
      <% end %>
      </ul>
    </div>
  </nav>
  <title>Destinations</title>
  <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track' => true %>
  <%= javascript_include_tag 'application', 'data-turbolinks-track' => true %>
  <%= csrf_meta_tags %>
</head>
<body>

<%= yield %>

</body>
</html>
        

destinations/app/views/users/edit.html.erb
<h1>Edit Page</h1>

<%= form_for @user do |f| %>
  <div>
    <%= f.text_field :profile_pic, placeholder: "Profile Photo" %>
  </div>
  <div>
    <%= f.text_field :first_name, placeholder: "First Name" %>
  </div>
  <div>
    <%= f.text_field :last_name, placeholder: "Last Name" %>
  </div>
  <div>
    <%= f.text_field :age, placeholder: "Age" %>
  </div>
  <div>
    <%= f.text_field :email, placeholder: "Email" %>
  </div>
  <div>
    <%= f.password_field :password, placeholder: "Password" %>
  </div>
  <div>
    <%= f.text_field :current_city, placeholder: "Current City" %>
  </div>
  <div>
    <%= f.text_field :description, placeholder: "Description" %>
  </div>
  <%= f.submit "Edit" %>
<% end %>

destinations/app/views/users/home.html.erb
<h1>Home</h1>

destinations/app/views/users/index.html.erb
<h1>Welcome to the Users Page</h1>

<% @users.each do |user| %>
	<ul>
		<li><%= link_to image_tag(user.profile_pic), user %> </li>
		<li><%= user.first_name %></li>
		<li><%= user.last_name %></li>
		<li><%= user.description %></li>
	</ul>
<% end %>

destinations/app/views/users/new.html.erb
<h1>Sign Up Page</h1>

<%= form_for @user do |f| %>
  <div>
    <%= f.text_field :profile_pic, placeholder: "Profile Photo" %>
  </div>
  <div>
    <%= f.text_field :first_name, placeholder: "First Name" %>
  </div>
  <div>
    <%= f.text_field :last_name, placeholder: "Last Name" %>
  </div>
  <div>
    <%= f.text_field :age, placeholder: "Age" %>
  </div>
  <div>
    <%= f.text_field :email, placeholder: "Email" %>
  </div>
  <div>
    <%= f.password_field :password, placeholder: "Password" %>
  </div>
  <div>
    <%= f.text_field :current_city, placeholder: "Current City" %>
  </div>
  <div>
    <%= f.text_area :description, placeholder: "Description" %>
  </div>
  <%= f.submit "Sign Up" %>
<% end %>

destinations/app/views/users/show.html.erb
<div>Welcome, <%= @user.first_name %>, <%= @user.last_name %></div>
  <div>Current city: <%= @user.current_city %></div>
  <div>Join date: <%= @user.created_at %></div>
  <img src="<%= @user.profile_pic %>"></div>

  <% @user.venues.each do |v| %>
  <ul>
  	<li>
  		<%= v.name %>
  	</li>
  	<li>
  		<%= v.city %>
  	</li>
  </ul>
  <% end %>

  

destinations/app/views/venues/index.html.erb
<h1>Venues</h1>

<% @venues.each do |venue| %>
	<ul>
		<li><%= link_to image_tag(venue.profile_pic), venue %></li>
		<li><%= venue.name %></li>
		<li><%= venue.city %></li>
	</ul>
<% end %>

destinations/app/views/venues/new.html.erb
<h1>Add a Venue</h1>

<%= form_for @venue do |form| %>

  <%= form.text_field :name, placeholder: "Venue Name" %>
  <%= form.text_field :street_one, placeholder: "123 Street Name" %>
  <%= form.text_field :street_two, placeholder: "Suite 123" %>
  <%= form.text_field :city, placeholder: "San Francisco" %>
  <%= form.text_field :state, placeholder: "California" %>
  <%= form.text_field :zipcode, placeholder: "12345" %>
  <%= form.text_field :phone_number, placeholder: "123-123-1234" %>
  <%= form.text_field :email, placeholder: "Contact email" %>
  <%= form.text_area :description, placeholder: "Cool bar", size: "24x6" %>
  <%= form.text_field :profile_pic, placeholder: "Photo URL" %>
  <%= form.submit "Save!" %>

<% end %>

destinations/app/views/venues/show.html.erb
<h1> <%= @venue.name %></h1>

<ul>
  <li> <%= @venue.street_one %></li>
  <li> <%= @venue.street_two %></li>
  <li> <%= @venue.city %></li>
  <li> <%= @venue.state %></li>
  <li> <%= @venue.zipcode %></li>
  <li> <%= @venue.phone_number %></li>
  <li> <%= @venue.email %></li>
  <li> <%= @venue.description %></li>
  <li> <%= @venue.profile_pic %></li>
</ul>